#pragma once

#include "cgfx/shader.h"
#include "cgfx/material.h"
#include "common.h"

#define PICA_CMD_CULLING 0x40
#define PICA_CMD_POLYGON_OFFSET_ENABLE 0x4C
#define PICA_CMD_POLYGON_OFFSET_ZSCALE 0x4D
#define PICA_CMD_POLYGON_OFFSET_ZBIAS 0x4E
#define PICA_CMD_TEX_UNITS_CONFIG 0x80
#define PICA_CMD_TEX_UNIT0_BORDER_COLOUR 0x81
#define PICA_CMD_TEX_UNIT0_SIZE 0x82
#define PICA_CMD_TEX_UNIT0_PARAM 0x83
#define PICA_CMD_TEX_UNIT0_LEVEL_OF_DETAIL 0x84
#define PICA_CMD_TEX_UNIT0_ADDRESS 0x85
#define PICA_CMD_TEX_UNIT0_TYPE 0x8E
#define PICA_CMD_TEX_UNIT1_BORDER_COLOUR 0x91
#define PICA_CMD_TEX_UNIT1_SIZE 0x92
#define PICA_CMD_TEX_UNIT1_PARAM 0x93
#define PICA_CMD_TEX_UNIT1_LEVEL_OF_DETAIL 0x94
#define PICA_CMD_TEX_UNIT1_ADDRESS 0x95
#define PICA_CMD_TEX_UNIT1_TYPE 0x96
#define PICA_CMD_TEX_UNIT2_BORDER_COLOUR 0x99
#define PICA_CMD_TEX_UNIT2_SIZE 0x9A
#define PICA_CMD_TEX_UNIT2_PARAM 0x9B
#define PICA_CMD_TEX_UNIT2_LEVEL_OF_DETAIL 0x9C
#define PICA_CMD_TEX_UNIT2_ADDRESS 0x9D
#define PICA_CMD_TEX_UNIT2_TYPE 0x9E
#define PICA_CMD_TEV_STAGE0_SOURCE 0xC0
#define PICA_CMD_TEV_STAGE0_OPERAND 0xC1
#define PICA_CMD_TEV_STAGE0_COMBINE 0xC2
#define PICA_CMD_TEV_STAGE0_CONSTANT 0xC3
#define PICA_CMD_TEV_STAGE0_SCALE 0xC4
#define PICA_CMD_TEV_STAGE1_SOURCE 0xC8
#define PICA_CMD_TEV_STAGE1_OPERAND 0xC9
#define PICA_CMD_TEV_STAGE1_COMBINE 0xCA
#define PICA_CMD_TEV_STAGE1_CONSTANT 0xCB
#define PICA_CMD_TEV_STAGE1_SCALE 0xCC
#define PICA_CMD_TEV_STAGE2_SOURCE 0xD0
#define PICA_CMD_TEV_STAGE2_OPERAND 0xD1
#define PICA_CMD_TEV_STAGE2_COMBINE 0xD2
#define PICA_CMD_TEV_STAGE2_CONSTANT 0xD3
#define PICA_CMD_TEV_STAGE2_SCALE 0xD4
#define PICA_CMD_TEV_STAGE3_SOURCE 0xD8
#define PICA_CMD_TEV_STAGE3_OPERAND 0xD9
#define PICA_CMD_TEV_STAGE3_COMBINE 0xDA
#define PICA_CMD_TEV_STAGE3_CONSTANT 0xDB
#define PICA_CMD_TEV_STAGE3_SCALE 0xDC
#define PICA_CMD_FRAGMENT_BUFFER_INPUT 0xE0
#define PICA_CMD_TEV_STAGE4_SOURCE 0xF0
#define PICA_CMD_TEV_STAGE4_OPERAND 0xF1
#define PICA_CMD_TEV_STAGE4_COMBINE 0xF2
#define PICA_CMD_TEV_STAGE4_CONSTANT 0xF3
#define PICA_CMD_TEV_STAGE4_SCALE 0xF4
#define PICA_CMD_TEV_STAGE5_SOURCE 0xF8
#define PICA_CMD_TEV_STAGE5_OPERAND 0xF9
#define PICA_CMD_TEV_STAGE5_COMBINE 0xFA
#define PICA_CMD_TEV_STAGE5_CONSTANT 0xFB
#define PICA_CMD_TEV_STAGE5_SCALE 0xFC
#define PICA_CMD_FRAGMENT_BUFFER_COLOUR 0xFD
#define PICA_CMD_COLOUR_OUTPUT_CONFIG 0x100
#define PICA_CMD_BLEND_CONFIG 0x101
#define PICA_CMD_COLOUR_LOGIC_OPERATION_CONFIG 0x102
#define PICA_CMD_BLEND_COLOUR 0x103
#define PICA_CMD_ALPHA_TEST_CONFIG 0x104
#define PICA_CMD_STENCIL_TEST_CONFIG 0x105
#define PICA_CMD_STENCIL_OPERATION_CONFIG 0x106
#define PICA_CMD_DEPTH_TEST_CONFIG 0x107
#define PICA_CMD_CULL_MODE_CONFIG 0x108
#define PICA_CMD_FRAME_BUFFER_INVALIDATE 0x110
#define PICA_CMD_FRAME_BUFFER_FLUSH 0x111
#define PICA_CMD_COLOUR_BUFFER_READ 0x112
#define PICA_CMD_COLOUR_BUFFER_WRITE 0x113
#define PICA_CMD_DEPTH_BUFFER_READ 0x114
#define PICA_CMD_DEPTH_BUFFER_WRITE 0x115
#define PICA_CMD_DEPTH_TEST_CONFIG2 0x126
#define PICA_CMD_FRAGMENT_SHADER_LOOK_UP_TABLE_CONFIG 0x1C5
#define PICA_CMD_FRAGMENT_SHADER_LOOK_UP_TABLE_DATA 0x1C8
#define PICA_CMD_LUT_SAMPLER_ABSOLUTE 0x1D0
#define PICA_CMD_LUT_SAMPLER_INPUT 0x1D1
#define PICA_CMD_LUT_SAMPLER_SCALE 0x1D2
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER_ADDRESS 0x200
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER_FORMAT_LOW 0x201
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER_FORMAT_HIGH 0x202
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER0_ADDRESS 0x203
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER0_PERMUTATION 0x204
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER0_STRIDE 0x205
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER1_ADDRESS 0x206
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER1_PERMUTATION 0x207
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER1_STRIDE 0x208
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER2_ADDRESS 0x209
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER2_PERMUTATION 0x20A
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER2_STRIDE 0x20B
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER3_ADDRESS 0x20C
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER3_PERMUTATION 0x20D
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER3_STRIDE 0x20E
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER4_ADDRESS 0x20F
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER4_PERMUTATION 0x210
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER4_STRIDE 0x211
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER5_ADDRESS 0x212
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER5_PERMUTATION 0x213
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER5_STRIDE 0x214
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER6_ADDRESS 0x215
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER6_PERMUTATION 0x216
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER6_STRIDE 0x217
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER7_ADDRESS 0x218
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER7_PERMUTATION 0x219
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER7_STRIDE 0x21A
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER8_ADDRESS 0x21B
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER8_PERMUTATION 0x21C
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER8_STRIDE 0x21D
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER9_ADDRESS 0x21E
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER9_PERMUTATION 0x21F
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER9_STRIDE 0x220
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER10ADDRESS 0x221
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER10PERMUTATION 0x222
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER10STRIDE 0x223
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER11ADDRESS 0x224
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER11PERMUTATION 0x225
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_BUFFER11STRIDE 0x226
#define PICA_CMD_INDEX_BUFFER_CONFIG 0x227
#define PICA_CMD_INDEX_BUFFER_TOTAL_VERTICES 0x228
#define PICA_CMD_BLOCK_END 0x23D
#define PICA_CMD_VERTEX_SHADER_TOTAL_ATTRIBUTES 0x242
#define PICA_CMD_VERTEX_SHADER_BOOLEAN_UNIFORMS 0x2B0
#define PICA_CMD_VERTEX_SHADER_INTEGER_UNIFORMS0 0x2B1
#define PICA_CMD_VERTEX_SHADER_INTEGER_UNIFORMS1 0x2B2
#define PICA_CMD_VERTEX_SHADER_INTEGER_UNIFORMS2 0x2B3
#define PICA_CMD_VERTEX_SHADER_INTEGER_UNIFORMS3 0x2B4
#define PICA_CMD_VERTEX_SHADER_INPUT_BUFFER_CONFIG 0x2B9
#define PICA_CMD_VERTEX_SHADER_ENTRY_POINT 0x2BA
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_PERMUTATION_LOW 0x2BB
#define PICA_CMD_VERTEX_SHADER_ATTRIBUTES_PERMUTATION_HIGH 0x2BC
#define PICA_CMD_VERTEX_SHADER_OUTMAP_MASK 0x2BD
#define PICA_CMD_VERTEX_SHADER_CODE_TRANSFER_END 0x2BF
#define PICA_CMD_VERTEX_SHADER_FLOAT_UNIFORM_CONFIG 0x2C0
#define PICA_CMD_VERTEX_SHADER_FLOAT_UNIFORM_DATA 0x2C1

#define PICA_VSH_ATTR_POSITION 0
#define PICA_VSH_ATTR_NORMAL 1
#define PICA_VSH_ATTR_TANGENT 2
#define PICA_VSH_ATTR_COLOUR 3
#define PICA_VSH_ATTR_TEXTURE_COORDINATE0 4
#define PICA_VSH_ATTR_TEXTURE_COORDINATE1 5
#define PICA_VSH_ATTR_TEXTURE_COORDINATE2 6
#define PICA_VSH_ATTR_BONE_INDEX 7
#define PICA_VSH_ATTR_BONE_WEIGHT 8
#define PICA_VSH_ATTR_USER_ATTRIBUTE0 9
#define PICA_VSH_ATTR_USER_ATTRIBUTE1 0xA
#define PICA_VSH_ATTR_USER_ATTRIBUTE2 0xB
#define PICA_VSH_ATTR_USER_ATTRIBUTE3 0xC
#define PICA_VSH_ATTR_USER_ATTRIBUTE4 0xD
#define PICA_VSH_ATTR_USER_ATTRIBUTE5 0xE
#define PICA_VSH_ATTR_USER_ATTRIBUTE6 0xF
#define PICA_VSH_ATTR_USER_ATTRIBUTE7 0x10
#define PICA_VSH_ATTR_USER_ATTRIBUTE8 0x11
#define PICA_VSH_ATTR_USER_ATTRIBUTE9 0x12
#define PICA_VSH_ATTR_USER_ATTRIBUTE10 0x13
#define PICA_VSH_ATTR_USER_ATTRIBUTE11 0x14
#define PICA_VSH_ATTR_INTERLEAVE 0x15
#define PICA_VSH_ATTR_QUANTITY 0x16

#define PICA_ATTR_FORMAT_TYPE_SIGNED_BYTE 0
#define PICA_ATTR_FORMAT_TYPE_UNSIGNED_BYTE 1
#define PICA_ATTR_FORMAT_TYPE_SIGNED_SHORT 2
#define PICA_ATTR_FORMAT_TYPE_FLOAT 3

#define PICA_INDEX_BUFFER_FORMAT_UBYTE 0
#define PICA_INDEX_BUFFER_FORMAT_USHORT 1

#define PICA_TEX_UNIT0 0
#define PICA_TEX_UNIT1 1
#define PICA_TEX_UNIT2 2

#define PICA_TEV_STAGE0 0
#define PICA_TEV_STAGE1 1
#define PICA_TEV_STAGE2 2
#define PICA_TEV_STAGE3 3
#define PICA_TEV_STAGE4 4
#define PICA_TEV_STAGE5 5

typedef struct {
  uint32_t type;
  uint32_t attr_length;
} pica_attribute_format;

typedef struct {
  uint8_t r;
  uint8_t g;
  uint8_t b;
  uint8_t d0;
  uint8_t d1;
  uint8_t fresnel;
} pica_fragment_sampler_abs;

#define PICA_CMDR_F32_UNIFORMS 96
#define PICA_CMDR_LUT_SIZE 256
#define PICA_CMDR_BUFFER_SIZE 0x10000

typedef struct {
  uint32_t num_f32_uniforms;
  float *f32_uniforms[PICA_CMDR_F32_UNIFORMS];
  uint32_t f32_uniform_size[PICA_CMDR_F32_UNIFORMS];
  uint32_t f32_uniform_index;
  float lut[PICA_CMDR_LUT_SIZE];
  uint32_t num_uniforms;
  float *uniforms;
  uint32_t lut_index;
  uint32_t consumed_words;
  uint32_t *command_buffer;
  uint8_t is_valid;
} pica_command_reader;

void pica_cmdr_new(FILE *file, uint32_t num_words, uint8_t ignore_alignment,
                   pica_command_reader *reader);
void pica_cmdr_destroy(pica_command_reader *reader);
depth_operation pica_cmdr_get_depth_test(pica_command_reader *reader);
blend_operation pica_cmdr_get_blend_operation(pica_command_reader *reader);
stencil_operation pica_cmdr_get_stencil_test(pica_command_reader *reader);
uint32_t pica_cmdr_get_tex_unit_address(pica_command_reader *reader, uint8_t unit);
texture_mapping pica_cmdr_get_tex_unit_mapper(pica_command_reader *reader, uint8_t unit);
uint32_t pica_cmdr_get_tex_unit_border_colour(pica_command_reader *reader, uint8_t unit);
size2d pica_cmdr_get_tex_unit_size(pica_command_reader *reader, uint8_t unit);
texture_combiner pica_cmdr_get_tev_stage(pica_command_reader *reader, uint8_t stage);
alpha_test pica_cmdr_get_alpha_test(pica_command_reader *reader);
